# NOTE: Humans must also update the library version in the tests section of this recipe
{% set version = "1.0.2" %}
# Look in the libavif top level CMakeLists.txt for the updated library
# version (not the same as the project version) to update parameters for existence checks
# The SO name changes every version https://github.com/AOMediaCodec/libavif/issues/799
{% set so_version = "16.0.1" %}
{% set so_major_version = so_version.split('.')[0] %}

package:
  name: libavif-split
  version: {{ version }}

source:
  url: https://github.com/AOMediaCodec/libavif/archive/refs/tags/v{{ version }}.tar.gz
  sha256: de8bf79488c5b523b77358df8b85ae69c3078e6b3f1636fc1f313f952269ad20
  patches:
    - 000-find-library.patch

build:
  number: 0

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - ninja
  host:
    - aom
    - dav1d
    # - libpng
    # - jpeg
    - rav1e  # OSX ARM missing, and Windows library locating error
    - svt-av1

outputs:
  - name: libavif
    build:
      run_exports:
        - {{ pin_subpackage('libavif' ~ so_major_version) }}   # [unix]
        - {{ pin_subpackage('libavif', max_pin='x.x.x') }}     # [win]
    files:
      - include/avif             # [unix]
      - Library\\include\\avif   # [win]
      - lib/libavif.so     # [linux]
      - lib/libavif.dylib  # [osx]
      - Library\\bin\\avif.dll   # [win]
      - Library\\lib\\avif.lib   # [win]
      - lib/pkgconfig/libavif.pc             # [unix]
      - Library\\lib\\pkgconfig\\libavif.pc  # [win]
      - lib/cmake/libavif             # [unix]
      - Library\\lib\\cmake\\libavif  # [win]
    requirements:
      build:
        - cmake
        - {{ compiler('c') }}
        - ninja
      host:
        - aom
        - dav1d
        # - libpng
        # - jpeg
        - rav1e
        - svt-av1
      run:
        - {{ pin_subpackage('libavif' ~ so_major_version, exact=True) }}  # [not win]
    test:
      commands:
        - test -f ${PREFIX}/include/avif/avif.h                         # [unix]
        - if not exist %PREFIX%\\Library\\include\\avif\\avif.h exit 1  # [win]
        - test -f ${PREFIX}/lib/libavif${SHLIB_EXT}                   # [unix]
        - test -f ${PREFIX}/lib/libavif.so.{{ so_major_version }}     # [linux]
        - test -f ${PREFIX}/lib/libavif.so.{{ so_version }}           # [linux]
        - test -f ${PREFIX}/lib/libavif.{{ so_major_version }}.dylib  # [osx]
        - test -f ${PREFIX}/lib/libavif.{{ so_version }}.dylib        # [osx]
        - if not exist %PREFIX%\\Library\\bin\\avif.dll exit 1        # [win]
        - if not exist %PREFIX%\\Library\\lib\\avif.lib exit 1        # [win]
        - test -f ${PREFIX}/lib/pkgconfig/libavif.pc                         # [unix]
        - if not exist %PREFIX%\\Library\\lib\\pkgconfig\\libavif.pc exit 1  # [win]
        - test -f ${PREFIX}/lib/cmake/libavif/libavif-config.cmake           # [unix]
        - test -f ${PREFIX}/lib/cmake/libavif/libavif-config-release.cmake   # [unix]
        - test -f ${PREFIX}/lib/cmake/libavif/libavif-config-version.cmake   # [unix]
        - if not exist %PREFIX%\\Library\\lib\\cmake\\libavif\\libavif-config.cmake exit 1          # [win]
        - if not exist %PREFIX%\\Library\\lib\\cmake\\libavif\\libavif-config-release.cmake exit 1  # [win]
        - if not exist %PREFIX%\\Library\\lib\\cmake\\libavif\\libavif-config-version.cmake exit 1  # [win]

  - name: libavif{{ so_major_version }}
    build:
      skip: true  # [win]
      run_exports:
        - {{ pin_subpackage('libavif' ~ so_major_version) }}
    files:
      - lib/libavif.so.{{ so_major_version }}     # [linux]
      - lib/libavif.so.{{ so_version }}           # [linux]
      - lib/libavif.{{ so_major_version }}.dylib  # [osx]
      - lib/libavif.{{ so_version }}.dylib        # [osx]
    requirements:
      build:
        - cmake
        - {{ compiler('c') }}
        - ninja
      host:
        - aom
        - dav1d
        # - libpng
        # - jpeg
        - rav1e
        - svt-av1
    test:
      commands:
        - test ! -f ${PREFIX}/include/avif/avif.h                           # [unix]
        - test ! -f ${PREFIX}/lib/libavif${SHLIB_EXT}                       # [unix]
        - test -f ${PREFIX}/lib/libavif.so.{{ so_major_version }}           # [linux]
        - test -f ${PREFIX}/lib/libavif.so.{{ so_version }}                 # [linux]
        - test -f ${PREFIX}/lib/libavif.{{ so_major_version }}.dylib        # [osx]
        - test -f ${PREFIX}/lib/libavif.{{ so_version }}.dylib              # [osx]
        - test ! -f ${PREFIX}/lib/pkgconfig/libavif.pc                      # [unix]
        - test ! -f ${PREFIX}/lib/cmake/libavif/libavif-config.cmake        # [unix]
        - test ! -f ${PREFIX}/lib/cmake/libavif/libavif-config-release.cmake  # [unix]
        - test ! -f ${PREFIX}/lib/cmake/libavif/libavif-config-version.cmake  # [unix]

about:
  home: https://github.com/AOMediaCodec/libavif
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A friendly, portable C implementation of the AV1 Image File Format
  description: |
    This library aims to be a friendly, portable C implementation of the AV1
    Image File Format, as described here
    <https://aomediacodec.github.io/av1-avif/>.

extra:
  recipe-maintainers:
    - carterbox
    - hmaarrfk
  feedstock-name: libavif
